import { describe, it, expect, vi, beforeEach } from "vitest";

// We test the helper functions by extracting the logic.
// Since the tool registers on an McpServer, we test the report generation indirectly
// by mocking the timeline-db and invoking the registered tool handler.

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { registerExportTimeline } from "../src/tools/export-timeline.js";

// Mock timeline-db
vi.mock("../src/lib/timeline-db.js", () => ({
  getTimeline: vi.fn().mockResolvedValue([
    {
      id: "1",
      timestamp: "2025-03-17T10:00:00Z",
      type: "prompt",
      project: "/test",
      branch: "main",
      session_id: "s1",
      source_file: "test.jsonl",
      source_line: 1,
      content: "Implement auth flow",
    },
    {
      id: "2",
      timestamp: "2025-03-17T11:00:00Z",
      type: "commit",
      project: "/test",
      branch: "main",
      session_id: "s1",
      source_file: "test.jsonl",
      source_line: 2,
      content: "feat: add auth middleware",
    },
    {
      id: "3",
      timestamp: "2025-03-17T12:00:00Z",
      type: "correction",
      project: "/test",
      branch: "main",
      session_id: "s1",
      source_file: "test.jsonl",
      source_line: 3,
      content: "Wrong import path used",
    },
    {
      id: "4",
      timestamp: "2025-03-18T09:00:00Z",
      type: "prompt",
      project: "/test",
      branch: "main",
      session_id: "s2",
      source_file: "test.jsonl",
      source_line: 4,
      content: "Fix auth bug",
    },
    {
      id: "5",
      timestamp: "2025-03-18T10:00:00Z",
      type: "error",
      project: "/test",
      branch: "main",
      session_id: "s2",
      source_file: "test.jsonl",
      source_line: 5,
      content: "TypeError: Cannot read property 'token'",
    },
  ]),
  listIndexedProjects: vi.fn().mockResolvedValue([{ project: "/test" }]),
}));

vi.mock("../src/lib/config.js", () => ({
  getRelatedProjects: vi.fn().mockReturnValue([]),
}));

describe("export_timeline", () => {
  let toolHandler: any;

  beforeEach(() => {
    // Capture the tool handler by mocking McpServer.tool
    const server = new McpServer({ name: "test", version: "1.0.0" });
    const originalTool = server.tool.bind(server);

    server.tool = ((...args: any[]) => {
      // The handler is the last argument
      toolHandler = args[args.length - 1];
      return originalTool(...args);
    }) as any;

    registerExportTimeline(server);
  });

  it("generates a markdown report with all sections", async () => {
    const result = await toolHandler({
      scope: "all",
      period: "week",
      offset: 0,
      save: false,
      include_commits: true,
      include_corrections: true,
      include_errors: true,
      include_chart: true,
    });

    const text = result.content[0].text;

    // Header
    expect(text).toContain("📊 Session Report:");
    expect(text).toContain("**Events:** 5");

    // Summary table
    expect(text).toContain("Total Events");
    expect(text).toContain("Prompts");
    expect(text).toContain("Correction Rate");

    // Activity chart
    expect(text).toContain("Activity Chart");
    expect(text).toContain("█");

    // Commits section
    expect(text).toContain("Recent Commits");
    expect(text).toContain("feat: add auth middleware");

    // Corrections section
    expect(text).toContain("Corrections & Lessons");
    expect(text).toContain("Wrong import path");

    // Errors section
    expect(text).toContain("Errors");
    expect(text).toContain("TypeError");

    // Footer
    expect(text).toContain("Generated by preflight");
  });

  it("returns empty message when no events", async () => {
    const { getTimeline } = await import("../src/lib/timeline-db.js");
    (getTimeline as any).mockResolvedValueOnce([]);

    const result = await toolHandler({
      scope: "all",
      period: "week",
      offset: 0,
      save: false,
      include_commits: true,
      include_corrections: true,
      include_errors: true,
      include_chart: true,
    });

    expect(result.content[0].text).toContain("No events found");
  });
});
